### ISSUE TITLE
SnappyData 1.3.0 always creates column names in lowercase even though create command has column names in uppercase.

### ISSUE THREAD

**Issue by parimalaadinarayan** [TIBCOSoftware/snappydata#1566]
Behavior mentioned in bug [https://github.com/TIBCOSoftware/snappydata/issues/1559](https://github.com/TIBCOSoftware/snappydata/issues/1559) is happening even in snappydata-1.3.0.
Tried with older version of jdbc i.e snappydata-jdbc_2.11-1.1.0.jar and newer version that comes with 1.3.0.
Below is the code snippet:
`ResultSet rs = statement.executeQuery("SELECT ch FROM " + "greetings" + " WHERE ch IS NOT NULL LIMIT 1");
            while(rs.next()){
                    String a = rs.getString("ch");
                    System.out.println(a);
                }`
1. Table "greetings" was created with column name "CH" in uppercase.
2. Select columname from table works for both upper and lower cases.
3.However resultset.getString(columnname) works if and only if columnname is passed in lowercase.
Lets us know if there are any settings to enable case insensitivity.

**Comment by sumwale** [comment]
@parimalaadinarayan Are you using the snappydata-jdbc_2.11-1.3.0.jar from https://github.com/TIBCOSoftware/snappydata/releases/tag/v1.3.0? You will need to remove all instances of the older JDBC jar from your classpath.

**Comment by parimalaadinarayan** [comment]
@sumwale Thanks, it worked after removing older JDBC jar from classpath.
